#!/usr/bin/env sh

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# aliases
rm $HOME/.aliases
ln -sf $DOTFILES/aliases/.aliases $HOME/.aliases

# zshrc
rm $HOME/.zshrc
ln -sf $DOTFILES/zsh/zshrc $HOME/.zshrc

# fzf
rm $HOME/.fzf.zsh
ln -sf $DOTFILES/fzf/.fzf.zsh $HOME/.fzf.zsh

# alacritty
rm -rf $HOME/.config/alacritty
ln -s $DOTFILES/alacritty $HOME/.config/alacritty

# tmux
ln -sf $DOTFILES/scripts/t $HOME/.local/bin/t
rm -rf $HOME/.tmux/plugins
ln -sf $DOTFILES/tmux/plugins $HOME/.tmux/plugins
ln -sf $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

# neovim 
## Optional with neovim, you can add harpoon
rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim


# NVM
# Create NVM directory if it doesn't exist
mkdir -p $HOME/.nvm

# Symlink default-packages for automatic installation
ln -sf $DOTFILES/nvm/default-packages $HOME/.nvm/default-packages

# Install NVM if not installed
if [ ! -d "$HOME/.nvm" ]; then
  echo "Installing NVM..."
  curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
else
  echo "NVM is already installed."
fi

# Load NVM (needed for further commands)
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Install latest LTS Node.js version (automatically installs `default-packages`)
nvm install --lts
nvm use --lts
nvm alias default node

echo "NVM and global packages setup complete!"

# WIP
# git

# TODO
# karabiner
# yabai
# skhd
# sketchybar
#   Fix current sketchybar icon beside wifi
